version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "4122:4122"
    restart: always
    depends_on:
      - pocketbase
    environment:
      - APP_ENV=production
      - POCKETBASE_URL=http://pocketbase:4123

  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile.pocketbase
    container_name: pocketbase
    ports:
      - "4123:4123"
    restart: always
